version: '3.4'
services:
  ism:
    image: schmidi/internet-speed-monitor
    environment:
      - INTERVAL=300
      - INFLUXDATABASENAME=ism
      - INFLUXHOST=localhost
      - INFLUXPORT=8086
      - INFLUXUSER=root
      - INFLUXPASS=toor
      - SERVER_ID=99
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 31m
volumes:
  data:
